-- 125_productos_fotos_drive.sql (2026-10-06)
--
-- Productos de panadería y perfumería armados con las fotos que el usuario
-- subió al Drive de la cuenta (el sufijo del nombre de cada archivo dice el
-- rubro). Solo datos, sin cambios de esquema. A pedido del usuario: llenar el
-- sitio de productos visibles, con nombre, descripción y opciones (sabor,
-- color, fragancia, tono...) que coincidan con lo que se ve en la foto.
--
-- ORDEN: aplicar DESPUÉS de que el deploy con public/img/productos/*.webp esté
-- en producción. Si se aplica antes, los productos salen con la imagen rota.
--
-- Comercios:
--   * Panadería El Sol (seed): sus productos Pan Francés, Medialunas y Pan
--     Integral dejan la foto genérica prod-panaderia.webp por una real, y suma
--     panes, bizcochos, facturas y tortas fritas. Torta de Ricota y Galletas
--     Surtidas quedan con la genérica: no hay una foto que les corresponda.
--   * Farmacia Central (seed, sin productos hasta hoy): higiene personal.
--   * Panadería y Confitería La Espiga (cuenta de prueba nueva,
--     proyectopdisc+laespiga@gmail.com): confitería, tortas y sándwiches.
--   * Perfumería Lavanda (cuenta de prueba nueva,
--     proyectopdisc+lavanda@gmail.com): perfumes, cuidado personal, pelo y uñas.
--   Las dos cuentas nuevas se crearon aparte (auth.users + auth.identities,
--   rol vendedor con la bandera app.role_change_authorized); acá se las busca
--   por email. Sin la cuenta, esta migración no inserta su comercio.
--
-- Los comercios de prueba no tienen alias bancario (no se inventa uno: un alias
-- falso podría ser el de alguien real). Por eso el trigger
-- products_require_transfer_alias (migración 107) se apaga mientras corre esta
-- migración y se vuelve a prender al final.
--
-- Las opciones tienen un tope de 40 caracteres (product_option_values_value_check).
-- Idempotente: un producto nuevo no se inserta si el comercio ya tiene uno con
-- el mismo título; las opciones de un producto existente se cargan solo si no
-- tiene ninguna.
--
-- Fotos que quedaron sin usar a propósito: las que tienen marca de agua de otro
-- sitio (alfajores chocolate, bolitas de fraile, brownie, facturas 2, pan
-- integral 2), las que no muestran lo que dice el nombre (pan integral 3 son
-- conchas, torta fritas dulces es otra masa, bizcocho salado 3 mezcla
-- cuernitos) y las de góndola con muchas marcas (productos nivea, tintes de pelo).

insert into public.stores (owner_id, name, status, category_slug, description, zone, hours, contact_method)
select u.id, v.name, 'approved', v.cat, v.descr, 'Baradero', to_jsonb(v.hours), 'none'
from (values
  ('proyectopdisc+laespiga@gmail.com', 'Panadería y Confitería La Espiga', 'panaderia',
   'Confitería de barrio: tortas, tartas, alfajores, bolas de fraile y sándwiches de miga para tus reuniones.',
   'Lunes a sábado de 7:00 a 13:00 y de 16:30 a 20:30'),
  ('proyectopdisc+lavanda@gmail.com', 'Perfumería Lavanda', 'perfumeria',
   'Perfumes, cuidado de la piel y todo para el pelo y las uñas, cerca de tu casa.',
   'Lunes a sábado de 9:00 a 13:00 y de 17:00 a 21:00')
) as v(email, name, cat, descr, hours)
join auth.users u on u.email = v.email
where not exists (select 1 from public.stores s where s.owner_id = u.id);

update public.stores set category_slug = 'panaderia',
  description = coalesce(description, 'Panes, medialunas y facturas recién horneados todos los días.')
 where id = 'ca554751-7417-4b10-88ff-c3ddeab66633' and category_slug is null;
update public.stores set category_slug = 'perfumeria',
  description = coalesce(description, 'Higiene personal y cuidado diario: pañuelos, protectores, toallitas y jabones.')
 where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12' and category_slug is null;

create function pg_temp.bl_add_options(p_product uuid, p_opts jsonb) returns void language plpgsql as $$
declare g jsonb; v text; gi int := 0; vi int; oid uuid;
begin
  if exists (select 1 from public.product_options where product_id = p_product) then return; end if;
  for g in select * from jsonb_array_elements(p_opts) loop
    insert into public.product_options (product_id, name, position) values (p_product, g->>'name', gi) returning id into oid;
    vi := 0;
    for v in select * from jsonb_array_elements_text(g->'values') loop
      insert into public.product_option_values (option_id, value, position) values (oid, v, vi);
      vi := vi + 1;
    end loop;
    gi := gi + 1;
  end loop;
end $$;

create function pg_temp.bl_set_images(p_product uuid, p_urls text[]) returns void language plpgsql as $$
begin
  delete from public.product_images where product_id = p_product;
  insert into public.product_images (product_id, url, position)
  select p_product, u, o - 1 from unnest(p_urls) with ordinality as t(u, o);
end $$;

create function pg_temp.bl_upsert_product(p_store uuid, p_cat text, p_title text, p_desc text, p_price int,
  p_stock int, p_urls text[], p_opts jsonb) returns void language plpgsql as $$
declare pid uuid;
begin
  if p_store is null then return; end if;
  if exists (select 1 from public.products where store_id = p_store and title = p_title) then return; end if;
  insert into public.products (seller_id, store_id, title, description, price, stock, image_url, category_id, is_active)
  select s.owner_id, s.id, p_title, p_desc, p_price, p_stock, p_urls[1],
         (select id from public.categories where slug = p_cat), true
    from public.stores s where s.id = p_store
  returning id into pid;
  perform pg_temp.bl_set_images(pid, p_urls);
  perform pg_temp.bl_add_options(pid, p_opts);
end $$;

create function pg_temp.bl_update_product(p_id uuid, p_desc text, p_urls text[], p_opts jsonb) returns void language plpgsql as $$
begin
  if not exists (select 1 from public.products where id = p_id) then return; end if;
  update public.products set image_url = p_urls[1], description = p_desc where id = p_id;
  perform pg_temp.bl_set_images(p_id, p_urls);
  perform pg_temp.bl_add_options(p_id, p_opts);
end $$;

alter table public.products disable trigger products_require_transfer_alias;

select pg_temp.bl_update_product('9e303867-6a9e-4c7d-8f7f-cc4556519750', 'Pan francés del día, crocante por fuera y tierno por dentro. Se vende por kilo, recién salido del horno.', array['/img/productos/pan-frances.webp'], '[]'::jsonb); -- Pan Francés 1kg
select pg_temp.bl_update_product('8f67c8b6-717a-402d-ba71-65186a4d301b', 'Doce medialunas recién horneadas. Elegí de manteca (dulces, con almíbar) o de grasa (saladas).', array['/img/productos/medialunas.webp', '/img/productos/medialunas-2.webp', '/img/productos/medialunas-3.webp', '/img/productos/medialunas-4.webp'], jsonb_build_array(jsonb_build_object('name', 'Tipo', 'values', jsonb_build_array('De manteca (dulces)', 'De grasa (saladas)')))); -- Docena de Medialunas
select pg_temp.bl_update_product('eb172135-8ca5-42a8-ae15-00ca8542bd09', 'Pan de molde integral con semillas por arriba, ideal para tostadas y sándwiches. Unidad de aprox. 500 g.', array['/img/productos/pan-integral-semillas.webp'], '[]'::jsonb); -- Pan Integral
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Pan de campo integral', 'Hogaza de harina integral, de corteza dorada y miga húmeda. Aprox. 800 g, rinde para toda la semana.', 3000, 20, array['/img/productos/pan-campo-integral.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Pan de manteca', 'Pan de manteca esponjoso, de miga suave y corteza brillante. Ideal para el desayuno o la merienda.', 2400, 20, array['/img/productos/pan-manteca.webp', '/img/productos/pan-manteca-2.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Bizcochos de grasa x 1/2 kg', 'Bizcochitos de grasa salados, hojaldrados y crocantes. Los clásicos para acompañar el mate.', 2200, 20, array['/img/productos/bizcochos-grasa.webp', '/img/productos/bizcochos-grasa-2.webp', '/img/productos/bizcochos-grasa-3.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Docena de facturas surtidas', 'Doce facturas surtidas: vigilantes con dulce de membrillo y con crema pastelera, cañoncitos, cuernitos y medialunas, según la hornada del día.', 5200, 20, array['/img/productos/facturas.webp', '/img/productos/facturas-2.webp', '/img/productos/facturas-3.webp', '/img/productos/facturas-4.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Medialunas de jamón y queso x6', 'Seis medialunas de manteca rellenas con jamón cocido y queso. Listas para calentar.', 5400, 20, array['/img/productos/medialunas-jyq.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'ca554751-7417-4b10-88ff-c3ddeab66633'), 'panaderia', 'Tortas fritas x6', 'Seis tortas fritas caseras, para los días de lluvia o cualquier mate. Elegí dulces (con azúcar) o saladas.', 2000, 20, array['/img/productos/tortas-fritas.webp', '/img/productos/tortas-fritas-2.webp', '/img/productos/tortas-fritas-3.webp', '/img/productos/tortas-fritas-4.webp', '/img/productos/tortas-fritas-5.webp'], jsonb_build_array(jsonb_build_object('name', 'Tipo', 'values', jsonb_build_array('Dulces (con azúcar)', 'Saladas'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Alfajores bañados x6', 'Seis alfajores de chocolate rellenos de dulce de leche. Elegí el baño: chocolate negro, chocolate blanco o mitad y mitad.', 4800, 20, array['/img/productos/alfajores-banados.webp', '/img/productos/alfajores-banados-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Baño', 'values', jsonb_build_array('Chocolate negro', 'Chocolate blanco', 'Mixtos'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Alfajores de maicena x6', 'Seis alfajores de maicena caseros, bien rellenos de dulce de leche y con coco rallado en el borde.', 3600, 20, array['/img/productos/alfajores-maicena.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Bolas de fraile x6', 'Seis bolas de fraile pasadas por azúcar. Elegí el relleno: dulce de leche, crema pastelera o mitad y mitad.', 4200, 20, array['/img/productos/bolitas-fraile.webp', '/img/productos/bolitas-fraile-2.webp', '/img/productos/bolitas-fraile-3.webp', '/img/productos/bolitas-fraile-4.webp'], jsonb_build_array(jsonb_build_object('name', 'Relleno', 'values', jsonb_build_array('Dulce de leche', 'Crema pastelera', 'Mixtas'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Brownies x4', 'Cuatro porciones de brownie húmedo de chocolate, con la costrita crocante arriba. Clásicos o con nueces.', 4000, 20, array['/img/productos/brownies.webp', '/img/productos/brownies-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Clásico', 'Con nueces'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Budín de chocolate', 'Budín húmedo de chocolate con trocitos de chocolate y azúcar impalpable por arriba. Aprox. 500 g.', 3500, 20, array['/img/productos/budin-chocolate.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Torta Selva Negra', 'Bizcochuelo de chocolate en capas con crema chantilly, virutas de chocolate y cerezas. Para 12 porciones.', 18000, 5, array['/img/productos/torta-selva-negra.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Torta de cumpleaños', 'Bizcochuelo de vainilla cubierto de crema chantilly, decorado con cerezas y tu mensaje escrito. Para 12 porciones; elegí el relleno.', 16000, 5, array['/img/productos/torta-cumpleanos.webp', '/img/productos/torta-cumpleanos-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Relleno', 'values', jsonb_build_array('Dulce de leche', 'Dulce de leche y durazno', 'Mousse de chocolate'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Torta brownie con merengue', 'Base de brownie con una montaña de merengue italiano con hilos de chocolate. Para 10 porciones.', 15000, 5, array['/img/productos/torta-brownie-merengue.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Torta de chocolate decorada', 'Torta de chocolate cubierta de granas, con copos de crema, trozos de chocolate y cerezas. Para 12 porciones.', 17000, 5, array['/img/productos/torta-chocolate.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Torta de frutas con crema', 'Bizcochuelo con crema chantilly, laterales de almendras fileteadas y frutillas y duraznos frescos arriba. Para 12 porciones.', 19000, 5, array['/img/productos/torta-frutas.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Tarta dulce', 'Tarta entera de masa sablée, para 8 porciones. Elegí el sabor.', 9000, 8, array['/img/productos/tartas-dulces.webp'], jsonb_build_array(jsonb_build_object('name', 'Sabor', 'values', jsonb_build_array('Lemon pie', 'Frutillas con crema', 'Pasta frola de membrillo', 'Frutos rojos'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Tarta de coco y dulce de leche', 'Tarta de masa dulce con una capa generosa de dulce de leche y cubierta de coco gratinado. Para 8 porciones.', 8000, 8, array['/img/productos/tarta-coco.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+laespiga@gmail.com' limit 1), 'panaderia', 'Sándwiches de miga x24', 'Veinticuatro sándwiches de miga triples, ideales para cumpleaños y reuniones. Elegí jamón y queso o surtidos (jamón, queso, tomate, lechuga y huevo), y el pan.', 12000, 10, array['/img/productos/sanguchitos-miga.webp', '/img/productos/sanguchitos-miga-2.webp', '/img/productos/sanguchitos-miga-3.webp', '/img/productos/sanguchitos-miga-4.webp', '/img/productos/sanguchitos-miga-5.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Jamón y queso', 'Surtidos')), jsonb_build_object('name', 'Pan', 'values', jsonb_build_array('Blanco', 'Blanco y negro'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Perfume Ciel eau de parfum 50 ml', 'Eau de parfum Ciel en frasco de 50 ml, con su caja. Elegí la fragancia.', 12500, 20, array['/img/productos/ciel-edp-50.webp', '/img/productos/ciel-edp-50-2.webp', '/img/productos/ciel-edp-50-3.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Rose', 'Nuit', 'Shine'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Perfume Ciel eau de parfum 80 ml', 'Eau de parfum Ciel en frasco de 80 ml, con su caja. Elegí la fragancia.', 16500, 20, array['/img/productos/ciel-edp-80.webp', '/img/productos/ciel-edp-80-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Floral', 'Paradise'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Colonia Ciel 250 ml', 'Eau de cologne Ciel en el clásico frasco de vidrio de 250 ml. Elegí la fragancia.', 9800, 20, array['/img/productos/ciel-colonia-250.webp', '/img/productos/ciel-colonia-250-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Crystal', 'Noir'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Set Ciel Floral con neceser', 'Set de regalo Ciel: eau de parfum Floral, desodorante en aerosol y neceser tornasolado "Time to Shine".', 19500, 8, array['/img/productos/ciel-set-time-to-shine.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Combo Ciel Shine: perfume + desodorante', 'Eau de parfum Ciel Shine 50 ml más el desodorante en aerosol de la misma fragancia.', 16500, 8, array['/img/productos/ciel-combo-shine.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Combo desodorantes Ciel Rose + Floral', 'Dos desodorantes en aerosol Ciel de 123 ml: uno Rose y uno Floral.', 7900, 20, array['/img/productos/ciel-desodorantes.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Body splash Natura Tododia 200 ml', 'Body splash Natura Tododia para perfumar la piel después del baño. Elegí la fragancia.', 14000, 20, array['/img/productos/natura-body-splash.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Cereza y avellana', 'Algodón', 'Ciruela y flor de vainilla', 'Frambuesa y pimienta rosa', 'Hojas de limón y guanábana'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Colonia Natura Ekos Frescor 150 ml', 'Desodorante colonia Natura Ekos Frescor, fresca y frutal. Elegí la fragancia.', 21000, 20, array['/img/productos/natura-ekos-frescor.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Cacao', 'Pitanga', 'Maracuyá', 'Castaña', 'Açaí'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Colonia Natura Kaiak para él 100 ml', 'Desodorante colonia Natura Kaiak masculino. Elegí la versión.', 23000, 20, array['/img/productos/natura-kaiak.webp'], jsonb_build_array(jsonb_build_object('name', 'Versión', 'values', jsonb_build_array('Kaiak clásico', 'Kaiak Océano', 'Kaiak Urbe', 'Kaiak Aventura'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Perfume Natura para ella', 'Perfumes femeninos de Natura. Elegí el que más te guste.', 24000, 20, array['/img/productos/natura-ella.webp'], jsonb_build_array(jsonb_build_object('name', 'Fragancia', 'values', jsonb_build_array('Kriska Shock', 'Kriska Drama', 'Humor'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Axe en barra Blue Lavender', 'Desodorante Axe en barra, fragancia Blue Lavender. Protección de larga duración.', 4500, 20, array['/img/productos/axe-barra.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Axe Apollo aerosol', 'Antitranspirante Axe Apollo en aerosol, 72 h de protección.', 3800, 20, array['/img/productos/axe-apollo.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Dove serum cream 50 g', 'Antitranspirante Dove en crema con niacinamida: seca rápido, 48 h de protección y previene el oscurecimiento.', 4900, 20, array['/img/productos/dove-serum-cream.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Nivea Men Black & White aerosol', 'Antitranspirante Nivea Men Black & White Invisible Original, 72 h, no mancha la ropa clara ni la oscura.', 3600, 20, array['/img/productos/nivea-men-bw.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Rexona Men aerosol', 'Antitranspirante Rexona Men en aerosol, 72 h de protección activada por el movimiento.', 3600, 20, array['/img/productos/rexona-men.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Desodorante Dove aerosol mujer', 'Antitranspirante Dove en aerosol, 72 h, con crema humectante. Elegí la variedad.', 3900, 20, array['/img/productos/dove-aerosol.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Go Fresh pera y aloe vera', 'Go Fresh granada', 'Invisible Dry', 'Original', 'Go Fresh pepino y té verde'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Crema facial Garnier Vitamina C FPS 30', 'Crema hidratante facial Garnier Skin Active Express Aclara con vitamina C y FPS 30.', 7900, 20, array['/img/productos/garnier-vitamina-c.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Crema corporal Nivea', 'Crema corporal Nivea con humectación de 48 h. Elegí la variedad: Hidratación Express (piel normal) o Milk Nutritiva (piel seca).', 7200, 20, array['/img/productos/nivea-corporal.webp', '/img/productos/nivea-corporal-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Hidratación Express', 'Milk Nutritiva'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Kit facial Nivea Rose Care x3', 'Rutina facial Nivea Rose Care con agua de rosas orgánica: 1) gel limpiador, 2) mist facial y 3) crema hidratante.', 15500, 8, array['/img/productos/nivea-rose-care-kit.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Combo facial Nivea: protector solar + Rose Care', 'Protector solar facial Nivea Sun FPS 50 control antibrillo, crema Rose Care, mist facial y agua micelar Rose Care.', 22000, 8, array['/img/productos/nivea-combo-facial.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Protector labial Nivea 4,8 g', 'Protector labial Nivea con 24 h de humectación, manteca de karité y un toque de color. Elegí el sabor.', 2900, 20, array['/img/productos/nivea-labial.webp', '/img/productos/nivea-labial-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Sabor', 'values', jsonb_build_array('Blackberry Shine', 'Cherry Shine'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Acondicionador Elvive Glycolic Gloss 370 ml 2x1', 'Llevás dos acondicionadores L''Oréal Elvive Glycolic Gloss de 370 ml: brillo cristalino sin peso.', 6900, 20, array['/img/productos/elvive-glycolic-2x1.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Shampoo Elvive Kera-Liso 200 ml', 'Shampoo L''Oréal Elvive Kera-Liso Nutri-Liss, para cabello alborotado o encrespado.', 4200, 20, array['/img/productos/elvive-kera-liso.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Kit Elvive Dream Liso', 'Rutina completa L''Oréal Elvive Dream Liso: shampoo 400 ml, acondicionador 400 ml, sérum y crema para peinar.', 24000, 8, array['/img/productos/elvive-dream-liso.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Kit Elvive Óleo Extraordinario nutrición', 'L''Oréal Elvive Óleo Extraordinario para cabello seco: shampoo 400 ml, acondicionador 400 ml y óleo 100 ml.', 21000, 8, array['/img/productos/elvive-oleo.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Combo Elvive: sérum Glycolic Gloss + Óleo Extraordinario', 'Sérum L''Oréal Elvive Glycolic Gloss 100 ml más el tratamiento Óleo Extraordinario.', 15000, 8, array['/img/productos/elvive-serum-oleo.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Acondicionador Sedal 650 ml', 'Tratamiento acondicionador Sedal Co-Creations de 650 ml, secado rápido. Elegí la línea.', 4600, 20, array['/img/productos/sedal-acondicionador.webp'], jsonb_build_array(jsonb_build_object('name', 'Línea', 'values', jsonb_build_array('Ceramidas', 'Óleo balance', 'Liso perfecto', 'Restauración instantánea', 'Rizos definidos'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Crema para peinar Sedal 300 ml', 'Crema para peinar Sedal. Elegí la línea según tu pelo.', 3900, 20, array['/img/productos/sedal-crema-peinar.webp'], jsonb_build_array(jsonb_build_object('name', 'Línea', 'values', jsonb_build_array('Ceramidas', 'Hialurónico + vitamina A', 'Liso perfecto', 'Rizos definidos', 'Jengibre y ricino'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Combo Sedal Rizos Definidos', 'Combo Sedal Rizos Definidos: shampoo, acondicionador, crema para peinar y máscara de tratamiento.', 13500, 8, array['/img/productos/sedal-rizos-combo.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Súper combo Garnier Fructis', 'Combo Garnier Fructis: crema para peinar Hidra Liso 10 en 1, crema para peinar Liso Coco, shampoo y acondicionador Oil Repair Liso Coco.', 14500, 8, array['/img/productos/fructis-combo.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Tintura Garnier Nutrisse', 'Coloración permanente Garnier Nutrisse con aceite de palta: 100% cobertura de canas. Elegí el tono.', 6500, 20, array['/img/productos/nutrisse.webp', '/img/productos/nutrisse-2.webp'], jsonb_build_array(jsonb_build_object('name', 'Tono', 'values', jsonb_build_array('1 Negro', '3 Castaño oscuro', '4 Castaño', '5 Castaño claro', '6 Rubio oscuro', '7 Rubio'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Kit para teñir el pelo', 'Bol y dos pinceles (uno con peine) para aplicar la tintura en casa.', 2500, 20, array['/img/productos/kit-tenir.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Esmalte semipermanente Meliné', 'Esmalte color gel Meliné para lámpara UV/LED, larga duración. Elegí el color.', 5500, 20, array['/img/productos/esmalte-meline.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Rosa', 'Violeta', 'Lila', 'Celeste', 'Verde lima'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Esmalte para uñas Tejar', 'Esmalte para uñas Tejar, secado rápido. Elegí el color.', 1800, 20, array['/img/productos/esmalte-tejar.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Rojo', 'Fucsia', 'Rosa', 'Lila', 'Azul', 'Verde', 'Amarillo', 'Coral', 'Naranja', 'Marrón', 'Blanco perlado', 'Plateado', 'Dorado', 'Glitter cobre'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Quitaesmaltes Algabo 3x2', 'Llevás tres quitaesmaltes Algabo y pagás dos: fortalecedor, con keratina y humectante.', 3600, 20, array['/img/productos/algabo-3x2.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Quitaesmaltes Cutex', 'Quitaesmaltes Cutex. Elegí la variedad.', 2300, 20, array['/img/productos/cutex.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Teens', 'Hipoalergénico', 'Fortalecedor', 'Humectante', 'Reparador'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Peine de madera', 'Peine de madera de dientes anchos, ideal para desenredar rulos sin romper el pelo.', 2500, 20, array['/img/productos/peine-madera.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Peine de plástico', 'Peine de plástico con mango, de dientes finos y gruesos. Elegí el color.', 900, 20, array['/img/productos/peine-plastico.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Turquesa', 'Blanco', 'Celeste', 'Rosa'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Cepillo desenredante', 'Cepillo desenredante con cerdas flexibles, en su blíster. Elegí el color.', 3500, 20, array['/img/productos/cepillo-desenredante.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Amarillo', 'Rosa'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Peine de cola', 'Peine de cola de dientes finos, para marcar rayas y hacer peinados. Elegí el color.', 1200, 20, array['/img/productos/peine-cola.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Celeste', 'Amarillo', 'Rosa', 'Lila'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Set de peluquería 20 piezas', 'Set negro de 20 piezas: cepillos, peines, pinceles de tintura, rociador, broches y gomitas.', 18000, 5, array['/img/productos/set-peluqueria.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+lavanda@gmail.com' limit 1), 'perfumeria', 'Cepillo definidor de rulos', 'Cepillo definidor para rulos y ondas, de cerdas separadas y mango largo.', 4800, 20, array['/img/productos/cepillo-rulos.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Pañuelos descartables Elegante 6x12', 'Seis paquetes de 12 pañuelos descartables Elegante, suaves y absorbentes.', 1500, 40, array['/img/productos/panuelos-elegante.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Pañuelos descartables Elite triple hoja x6', 'Seis paquetes de pañuelos descartables Elite de triple hoja.', 1700, 40, array['/img/productos/panuelos-elite.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Pañuelos descartables Felpita Infinity 6x10', 'Seis paquetes de 10 pañuelos descartables Felpita Infinity de doble hoja.', 1400, 40, array['/img/productos/panuelos-felpita.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Protectores diarios Carefree Todos los días', 'Protectores diarios Carefree Todos los días, finitos y respirables.', 2600, 40, array['/img/productos/carefree.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Protectores diarios Doncella anatómicos x20', 'Veinte protectores diarios Doncella anatómicos, con tela extra suave y perfume.', 1900, 40, array['/img/productos/doncella.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Toallitas LadySoft Comfort Soft con alas x8', 'Ocho toallitas femeninas LadySoft Comfort Soft con alas y tela suave.', 2200, 40, array['/img/productos/ladysoft.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Toallitas Nosotras Clásica Suave x8', 'Ocho toallitas femeninas Nosotras Clásica Suave, con alas, para flujo medio.', 2000, 40, array['/img/productos/nosotras.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Jabón Dove Pink pack x4', 'Cuatro jabones de tocador Dove Pink (rosa) con 1/4 de crema humectante.', 4500, 30, array['/img/productos/dove-pink-x4.webp'], '[]'::jsonb);
select pg_temp.bl_upsert_product((select id from public.stores where id = 'c61d5b9f-1bf8-4b03-96d4-633cfc061b12'), 'perfumeria', 'Jabón de tocador Dove 90 g', 'Jabón de tocador Dove con crema humectante. Elegí la variedad.', 1300, 40, array['/img/productos/dove-jabon.webp'], jsonb_build_array(jsonb_build_object('name', 'Variedad', 'values', jsonb_build_array('Original', 'Relaxing (coco)', 'Refreshing (pepino y té verde)', 'Nourishing', 'Manteca de karité', 'Restoring'))));

alter table public.products enable trigger products_require_transfer_alias;
