-- 129_productos_ropa_drive.sql (2026-10-08)
--
-- Productos de ropa armados con las fotos de la carpeta "Ropa" del Drive de la
-- cuenta. Solo datos, sin cambios de esquema. Mismo criterio que la 125: nombre,
-- descripción y opciones (color, talle, estampado) salen de lo que se ve en
-- cada foto, no del nombre del archivo.
--
-- ORDEN: aplicar DESPUÉS de que el deploy con public/img/productos/*.webp esté
-- en producción. Si se aplica antes, los productos salen con la imagen rota.
--
-- Comercios:
--   * Indumentaria La Moda (seed): sus 4 productos con fotos de origen dudoso
--     (jean, medias, campera, remera; ver migración 120) pasan a fotos del
--     Drive. El título cambia solo donde la foto muestra otra cosa (las medias
--     son Nike caña alta, no un pack de 3). Zapatillas Urbanas no se toca.
--     Suma ropa de hombre/unisex y accesorios de invierno, y pasa a la
--     categoría Ropa (estaba en NULL, como todas las tiendas de seed).
--   * Boutique Amapola (cuenta de prueba nueva, proyectopdisc+amapola@gmail.com):
--     ropa de mujer. La cuenta se creó aparte (auth.users + auth.identities, rol
--     vendedor con la bandera app.role_change_authorized); acá se la busca por
--     email. Sin la cuenta, esta migración no inserta su comercio.
--
-- Ningún comercio de prueba tiene alias bancario (no se inventa uno), así que
-- el trigger products_require_transfer_alias (migración 107) se apaga mientras
-- corre esta migración y se vuelve a prender al final.
--
-- Idempotente: un producto nuevo no se inserta si el comercio ya tiene uno con
-- el mismo título; las opciones de un producto existente se cargan solo si no
-- tiene ninguna.
--
-- Fotos sin usar a propósito: jean mujer, pollera jean mujer, pollera jean
-- mujer 2 y remera gatito pixelado (marca de agua de Xiaohongshu), remera
-- JesusJesus (logo "Y2KCHAOS" de otra tienda) y pijama rosa combo mujer (foto
-- sacada adentro de un local H&M).

insert into public.stores (owner_id, name, status, category_slug, description, zone, hours, contact_method)
select u.id, 'Boutique Amapola', 'approved', 'ropa',
  'Ropa de mujer para todos los días: remeras, jeans, sweaters, vestidos y pijamas.',
  'Baradero', to_jsonb('Lunes a sábado de 9:30 a 13:00 y de 17:00 a 21:00'::text), 'none'
from auth.users u
where u.email = 'proyectopdisc+amapola@gmail.com'
  and not exists (select 1 from public.stores s where s.owner_id = u.id);

update public.stores set category_slug = 'ropa',
  description = coalesce(description, 'Ropa de hombre y básicos para todos: remeras, jeans, camperas, buzos y accesorios de invierno.')
 where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391' and category_slug is null;

create function pg_temp.bl_add_options(p_product uuid, p_opts jsonb) returns void language plpgsql as $$
declare g jsonb; v text; gi int := 0; vi int; oid uuid;
begin
  if exists (select 1 from public.product_options where product_id = p_product) then return; end if;
  for g in select * from jsonb_array_elements(p_opts) loop
    insert into public.product_options (product_id, name, position) values (p_product, g->>'name', gi) returning id into oid;
    vi := 0;
    for v in select * from jsonb_array_elements_text(g->'values') loop
      insert into public.product_option_values (option_id, value, position) values (oid, v, vi);
      vi := vi + 1;
    end loop;
    gi := gi + 1;
  end loop;
end $$;

create function pg_temp.bl_set_images(p_product uuid, p_urls text[]) returns void language plpgsql as $$
begin
  delete from public.product_images where product_id = p_product;
  insert into public.product_images (product_id, url, position)
  select p_product, u, o - 1 from unnest(p_urls) with ordinality as t(u, o);
end $$;

create function pg_temp.bl_upsert_product(p_store uuid, p_cat text, p_title text, p_desc text, p_price int,
  p_stock int, p_urls text[], p_opts jsonb) returns void language plpgsql as $$
declare pid uuid;
begin
  if p_store is null then return; end if;
  if exists (select 1 from public.products where store_id = p_store and title = p_title) then return; end if;
  insert into public.products (seller_id, store_id, title, description, price, stock, image_url, category_id, is_active)
  select s.owner_id, s.id, p_title, p_desc, p_price, p_stock, p_urls[1],
         (select id from public.categories where slug = p_cat), true
    from public.stores s where s.id = p_store
  returning id into pid;
  perform pg_temp.bl_set_images(pid, p_urls);
  perform pg_temp.bl_add_options(pid, p_opts);
end $$;

-- A diferencia de la 125, acá también se cambia el título: la foto nueva manda.
create function pg_temp.bl_update_product(p_id uuid, p_title text, p_desc text, p_urls text[], p_opts jsonb) returns void language plpgsql as $$
begin
  if not exists (select 1 from public.products where id = p_id) then return; end if;
  update public.products set title = p_title, image_url = p_urls[1], description = p_desc where id = p_id;
  perform pg_temp.bl_set_images(p_id, p_urls);
  perform pg_temp.bl_add_options(p_id, p_opts);
end $$;

alter table public.products disable trigger products_require_transfer_alias;

-- Indumentaria La Moda
select pg_temp.bl_update_product('f26ac687-c185-49a1-b4d4-480e0ce190ac', 'Remera Básica Algodón', 'Remera lisa de algodón, cuello redondo y manga corta. Colores vivos para combinar con todo.', array['/img/productos/remera-basica-algodon.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Naranja', 'Verde', 'Violeta', 'Azul', 'Fucsia', 'Negro')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_update_product('7ab20ebc-1b39-47da-b0e3-41ee6e8702ea', 'Pantalón Jean Clásico', 'Jean de corte recto, cinco bolsillos y etiqueta de cuero atrás. Viene en negro, azul oscuro, azul medio y crudo.', array['/img/productos/jean-recto-hombre.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Azul oscuro', 'Azul medio', 'Crudo')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('38', '40', '42', '44', '46'))));
select pg_temp.bl_update_product('b289cbe7-daa7-46d0-9b01-51d556462007', 'Campera de Abrigo', 'Campera puffer acolchada, bien abrigada para el invierno. Los modelos claros y los verdes vienen con capucha; el negro y el crema, con cuello alto.', array['/img/productos/campera-puffer.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Gris topo', 'Marrón', 'Blanco', 'Verde salvia', 'Negro', 'Crema')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_update_product('1c1a67d8-cc54-42fe-a158-6ed9f7372358', 'Medias Nike caña alta', 'Medias de algodón caña alta, con puño acanalado y el logo de Nike tejido. Precio por par.', array['/img/productos/medias-nike.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Verde oliva', 'Marrón', 'Batik blanco', 'Camel', 'Nude')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('35-38', '39-42', '43-46'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Pijama remera y pantalón escocés', 'Pijama de hombre: remera azul marino con bolsillo y pantalón largo escocés gris y azul, con cintura de cordón.', 28000, 15, array['/img/productos/pijama-hombre-escoces.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Camisa de vestir rosa', 'Camisa de hombre manga larga, rosa claro, con cuello italiano y puños con botón.', 32000, 15, array['/img/productos/camisa-rosa.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Camisa entallada azul marino', 'Camisa de hombre entallada, azul marino, de tela con brillo suave. Para la oficina o una salida.', 32000, 15, array['/img/productos/camisa-azul-entallada.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Combo remera y pantalón negro', 'Conjunto todo negro como el de la foto: remera de algodón al cuerpo y pantalón de vestir recto.', 45000, 15, array['/img/productos/combo-remera-pantalon-negro.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Jean gris recto', 'Jean gris oscuro de corte recto y tiro medio, con cinco bolsillos.', 40000, 15, array['/img/productos/jean-gris-recto.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('38', '40', '42', '44', '46'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Jean ancho negro', 'Jean negro de corte ancho, con costuras claras en contraste.', 42000, 15, array['/img/productos/jean-ancho-negro.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('38', '40', '42', '44', '46'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Sweater tejido marrón', 'Sweater de hilo grueso con punto acanalado, cuello redondo y puños elastizados. Color marrón café.', 42000, 15, array['/img/productos/sweater-marron.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Polera tejida negra con trenzas', 'Polera de hilo grueso con tejido trenzado y cuello alto. Color negro.', 45000, 15, array['/img/productos/polera-negra-trenzada.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Campera puffer blanca', 'Campera puffer corta, blanca, con cuello alto, cierre y puños elastizados.', 70000, 15, array['/img/productos/campera-puffer-blanca.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Pantalón Adidas de tres tiras', 'Pantalón deportivo Adidas negro de pierna ancha, con las tres tiras blancas a los costados y cintura elastizada.', 48000, 15, array['/img/productos/pantalon-adidas.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Campera deportiva Adidas', 'Campera Adidas negra con cierre, cuello alto y las tres tiras blancas en las mangas.', 55000, 15, array['/img/productos/campera-adidas.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Pantalón carpintero Carhartt', 'Pantalón de trabajo Carhartt de corte recto, con bolsillos de carpintero y presilla para martillo.', 50000, 15, array['/img/productos/pantalon-carpintero.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Marrón oscuro', 'Verde oliva', 'Camel', 'Gris claro')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('38', '40', '42', '44', '46'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Buzo Nike medio cierre', 'Buzo Nike de friza con medio cierre y cuello alto, logo bordado en el pecho.', 45000, 15, array['/img/productos/buzo-medio-cierre-nike.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Blanco', 'Negro')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Remera lisa hombre', 'Remera de algodón de hombre, cuello redondo y manga corta, con un pequeño logo bordado.', 15000, 15, array['/img/productos/remera-lisa-hombre.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Azul acero', 'Azul grisáceo', 'Blanco crudo', 'Celeste')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Campera aviador con corderito', 'Campera aviador negra de cuero ecológico, con cuello, puños y forro de corderito.', 85000, 15, array['/img/productos/campera-aviador.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Jogging Nike de friza', 'Jogging Nike de friza con cintura elastizada y logo bordado.', 38000, 15, array['/img/productos/jogging-nike.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Gris', 'Marrón', 'Negro', 'Crema')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Chaleco de hilo escote en V', 'Chaleco de hilo trenzado blanco, con escote en V y guardas azul marino en el cuello, la sisa y la cintura.', 38000, 15, array['/img/productos/chaleco-hilo.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Jean beige recto', 'Jean color beige de corte recto, cinco bolsillos y etiqueta de cuero atrás.', 42000, 15, array['/img/productos/jean-beige.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('38', '40', '42', '44', '46'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Campera de friza gris con capucha', 'Campera de friza gris melange, con capucha, cierre y bolsillo canguro.', 40000, 15, array['/img/productos/campera-friza-gris.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Gorro de lana tejido', 'Gorro de lana con tejido trenzado y doblez, con logo bordado. Talle único.', 15000, 15, array['/img/productos/gorro-lana.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Gris', 'Azul marino', 'Crudo', 'Negro'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Gorra con visera', 'Gorra de gabardina con visera curva y logo bordado al frente. Se ajusta atrás.', 18000, 15, array['/img/productos/gorra.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Verde oliva', 'Bordó', 'Blanco', 'Crudo', 'Azul marino', 'Marrón', 'Beige'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Bufanda con flecos', 'Bufanda larga y suave, de tejido abrigado, con flecos trenzados en las puntas.', 22000, 15, array['/img/productos/bufanda-flecos.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Crudo', 'Suela', 'Gris'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Chaleco puffer', 'Chaleco puffer acolchado con cuello alto y cierre. Abriga sin sumar mangas.', 50000, 15, array['/img/productos/chaleco-puffer.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Crudo', 'Gris oscuro', 'Negro')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Buzo canguro blanco', 'Buzo de friza blanco, liso, con capucha y bolsillo canguro.', 35000, 15, array['/img/productos/buzo-canguro-blanco.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Campera de friza beige', 'Campera de friza beige con cierre, cuello alto y bolsillos al costado.', 48000, 15, array['/img/productos/campera-friza-beige.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Sweater trenzado crudo', 'Sweater de hilo color crudo con tejido trenzado, cuello redondo y un pequeño logo bordado.', 45000, 15, array['/img/productos/sweater-trenzado-crudo.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Remera oversize negra estampada', 'Remera negra oversize con estampa roja y blanca de letras japonesas y una ilustración.', 20000, 15, array['/img/productos/remera-oversize-japonesa.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Remera negra New York', 'Remera negra con estampa de Nueva York: la Estatua de la Libertad y los edificios.', 18000, 15, array['/img/productos/remera-new-york.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Pack x4 remeras lisas', 'Cuatro remeras lisas de algodón: una negra, una marrón, una beige y una blanca.', 42000, 15, array['/img/productos/pack-4-remeras.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));
select pg_temp.bl_upsert_product((select id from public.stores where id = 'd3c49d93-ca28-4e69-9825-ba77821ef391'), 'ropa', 'Pack x3 remeras lisas', 'Tres remeras lisas de algodón: una negra, una crudo y una marrón.', 33000, 15, array['/img/productos/pack-3-remeras.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('S', 'M', 'L', 'XL'))));

-- Boutique Amapola
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera acanalada con moñito', 'Remera blanca de morley acanalado, con ribete negro en el cuello, un moñito y terminación de puntilla en las mangas.', 16000, 15, array['/img/productos/remera-coquette.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera manga larga básica', 'Remera de manga larga al cuerpo, cuello redondo, de tela suave.', 17000, 15, array['/img/productos/remera-manga-larga.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Azul marino', 'Marrón', 'Nude', 'Blanco')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Jean wide leg nevado', 'Jean de pierna bien ancha, lavado nevado muy claro.', 42000, 15, array['/img/productos/jean-wide-leg-nevado.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('36', '38', '40', '42', '44'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Polera de morley', 'Polera de manga larga al cuerpo, con cuello alto.', 18000, 15, array['/img/productos/polera-morley.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Gris topo', 'Negro', 'Blanco', 'Marrón', 'Azul marino')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Pijama de lunas y estrellas x3', 'Pijama de tres piezas: musculosa negra de breteles finos, short y pantalón largo blancos con lunas y estrellas, con moño en la cintura.', 32000, 15, array['/img/productos/pijama-lunas.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Pantalón de pijama Hello Kitty', 'Pantalón de pijama de polar, bien abrigado, estampado con Hello Kitty.', 22000, 15, array['/img/productos/pantalon-pijama-hello-kitty.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Rosa', 'Negro', 'Blanco')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Baby tee lisa', 'Remera corta y al cuerpo, de algodón, manga corta.', 14000, 15, array['/img/productos/baby-tee.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Crudo', 'Marrón', 'Rosa', 'Gris', 'Blanco', 'Rojo')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Sweater oversize de hilo', 'Sweater de hilo con tejido acanalado, cuello redondo y calce holgado.', 40000, 15, array['/img/productos/sweater-oversize.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Verde oliva', 'Blanco', 'Crema', 'Celeste')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Vestido largo floreado', 'Vestido largo con mangas abullonadas y escote cuadrado o halter, según el estampado.', 45000, 15, array['/img/productos/vestido-floreado.webp'], jsonb_build_array(jsonb_build_object('name', 'Estampado', 'values', jsonb_build_array('Flores azules', 'Florcitas azules', 'Flores en crudo', 'Celeste floreado', 'Rosas', 'Negro con florcitas')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Body manga larga', 'Body de manga larga al cuerpo, cuello redondo.', 20000, 15, array['/img/productos/body-manga-larga.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Marrón', 'Blanco')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Top de un hombro', 'Top blanco asimétrico, con un solo hombro.', 16000, 15, array['/img/productos/top-un-hombro.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Campera de cuero ecológico con cinturón', 'Campera negra de cuero ecológico, corta, con cuello camisero, cierre y cinturón en la cintura.', 75000, 15, array['/img/productos/campera-cuero-cinturon.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Jean recto con strass', 'Jean azul de corte recto con strass brillantes en todo el pantalón.', 52000, 15, array['/img/productos/jean-strass.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('36', '38', '40', '42', '44'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Pantalón sastrero', 'Pantalón de vestir de tiro alto, con pinzas y pierna recta.', 38000, 15, array['/img/productos/pantalon-sastrero.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Beige', 'Blanco')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('36', '38', '40', '42', '44'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Jogging ancho gris', 'Jogging de friza gris melange, de pierna ancha, con cordón en la cintura y costuras al frente.', 32000, 15, array['/img/productos/jogging-ancho-gris.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Jean wide leg animal print', 'Jean de pierna ancha con estampado animal print.', 45000, 15, array['/img/productos/jean-animal-print.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('36', '38', '40', '42', '44'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Jean wide leg celeste', 'Jean celeste de pierna ancha y tiro medio.', 44000, 15, array['/img/productos/jean-wide-leg-celeste.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('36', '38', '40', '42', '44'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Polera de hilo acanalada', 'Polera de hilo con tejido acanalado y cuello alto.', 30000, 15, array['/img/productos/polera-hilo.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Azul petróleo', 'Blanco', 'Rosa viejo', 'Crema', 'Marrón')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Conjunto musculosa y short', 'Conjunto de musculosa rosa con ribetes marrones y short marrón con ribetes rosas.', 26000, 15, array['/img/productos/conjunto-musculosa-short.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Top halter', 'Top de escote halter, que se ata en el cuello.', 13000, 15, array['/img/productos/top-halter.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Blanco', 'Marrón')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Musculosa fruncida negra', 'Musculosa negra al cuerpo, de escote redondo, con frunce a los costados.', 12000, 15, array['/img/productos/musculosa-fruncida.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Combo x2 musculosas acanaladas', 'Dos musculosas de morley acanalado: una negra y una blanca.', 18000, 15, array['/img/productos/combo-musculosas.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Baby tee estampa gatito', 'Remera corta gris claro con la estampa de un gatito en blanco y negro.', 17000, 15, array['/img/productos/remera-gatito.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera marrón con moño', 'Remera marrón con un moño y un corazoncito estampados en dorado.', 17000, 15, array['/img/productos/remera-mono-dorado.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera blanca con beso', 'Remera blanca con un beso rojo estampado en el pecho.', 17000, 15, array['/img/productos/remera-beso.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Campera de friza con lunares', 'Campera crudo con lunares negros, con cierre, cuello alto y bolsillos.', 42000, 15, array['/img/productos/campera-lunares.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera marrón con mariposa', 'Remera marrón con una mariposa negra estampada en el pecho.', 17000, 15, array['/img/productos/remera-mariposa.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera bordó con corazones', 'Remera bordó con dos corazones dibujados en blanco.', 17000, 15, array['/img/productos/remera-corazones.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera ranglan bicolor', 'Remera blanca con mangas ranglan y cuello marrones, con un dibujo chiquito en el pecho.', 18000, 15, array['/img/productos/remera-ranglan.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera Vintage estampada', 'Remera crudo con cuello y puños marrones y estampa de un auto antiguo con la palabra Vintage.', 19000, 15, array['/img/productos/remera-vintage.webp'], jsonb_build_array(jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera lisa color pastel', 'Remera lisa de algodón, cuello redondo, en colores pastel.', 15000, 15, array['/img/productos/remera-pastel.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Rosa', 'Celeste', 'Lila', 'Crema')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));
select pg_temp.bl_upsert_product((select s.id from public.stores s join auth.users u on u.id = s.owner_id where u.email = 'proyectopdisc+amapola@gmail.com' limit 1), 'ropa', 'Remera corta entallada', 'Remera corta de manga corta, entallada, de algodón con elastano.', 14000, 15, array['/img/productos/remera-corta-entallada.webp'], jsonb_build_array(jsonb_build_object('name', 'Color', 'values', jsonb_build_array('Negro', 'Blanco', 'Celeste', 'Rosa', 'Crema', 'Gris topo')), jsonb_build_object('name', 'Talle', 'values', jsonb_build_array('XS', 'S', 'M', 'L'))));

alter table public.products enable trigger products_require_transfer_alias;
